version: 0.2

phases:
  install:
    commands:
      # Update libs
      - apt-get update
  build:
    commands:
      - echo Pre_build Phase
      - yarn install
      - yarn build
      - pwd

artifacts:
  paths:
      - dist/
