version: 0.2

phases:
  install:
    commands:
      # Update libs
      - apt-get update
  build:
    commands:
      - echo Pre_build Phase
      - yarn install
      - yarn build
      - cd dist
      -  aws s3 sync s3://testdeploymentvue --recursive
      - echo Build completed on `date`

artifacts:
  files:
    - '/'
  discard-paths: yes
  base-directory: 'dist*'
